[package]
name = "game"
version = "0.1.0"
authors = ["Jared James <mhskripters@gmail.com>"]
edition = "2018"

[dependencies]
termion = { git = "https://github.com/mcgoo/termion", branch = "windows" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"